- hosts: facecompare
  remote_user: root
  roles:
  - roles

  tasks:
  - name: start docker-compose facecompare
    shell: cd {{GosunBigDataServiceDir}}/analysis/facecompare; docker-compose up -d
    tags:
    - start docker-compose