- hosts: peoman
  remote_user: root
  roles:
  - roles

  tasks:
  - name: start docker-compose peoman
    shell: cd {{GosunBigDataServiceDir}}/analysis/peoman; docker-compose up -d
    tags:
    - start peoman-worker