- hosts: docker_gpu_servers
  remote_user: root
  roles:
  - roles

  tasks:
   - name: nvidia mashion install docker
     unarchive: src={{AnsibleDir}}/roles/files/docker-gpu.tar.gz dest={{BigdataDir}}
   - name: install docker
     shell: sh {{BigdataDir}}/docker-gpu/bin/docker-ce.sh
   - name: start docker
     shell: systemctl start docker
     tags: 
      - start docker
   - name: install docker-compose
     shell: mv {{AnsibleDir}}/roles/files/docker-compose  /usr/local/bin
     tags:
      - start docker-compose
   
  
  
