- hosts: hadoop_servers
  remote_user: root
  roles:
  - roles

  tasks:
   - name: start namenode
     shell: source /etc/profile; sh {{BigdataDir}}/hadoop/sbin/start-dfs.sh
     become: true
     become_method: su
     become_user: root
     when: namenode_active == "true"
     tags:
      - start hadoop


