- hosts: kafka_servers
  remote_user: root
  roles:
  - roles

  tasks:
   - name: source env
     shell: source /etc/profile
   - name: chmod +x
     shell: chmod +x {{BigdataDir}}/kafka/bin/*
   - name: stop kafka
     shell: source /etc/profile; sh {{BigdataDir}}/kafka/bin/kafka-server-stop.sh
     tags:
     - stop kafka

