- hosts: spark_servers
  remote_user: root
  roles:
  - roles

  tasks:
   - name: start spark cluster
     shell: source /etc/profile; sh {{BigdataDir}}/spark/sbin/start-all.sh
     tags:
      - start spark

