version: '2.3'

services:

  kibana:
    image: ${DOCKER_REPOSITOR}/hzgc/kibaba:5.5.0
    depends_on:
    - esearch
    container_name: kibana
    restart: always
    environment:
    - SERVER_NAME=$DOCKER_HOST_IP
    - ELASTICSEARCH_URL=http://${ES_HOST}:${ES_PORT}
    - TZ=Asia/Shanghai
    ports:
    - "5601:5601"
    volumes:
    - /etc/localtime:/etc/localtime:ro

  collect:
    image: ${DOCKER_REPOSITOR}/hzgc/collect:${VERSION}
    depends_on:
    - zookeeper
    - eureka
    - mysql
    container_name: collect
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - TZ=Asia/Shanghai
    network_mode: "host"
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/collect/log:/log
    - /usr/lib64/ld-linux-x86-64.so.2:/lib/ld-linux-x86-64.so.2
    - /etc/localtime:/etc/localtime:ro

  peoman-worker:
    image: ${DOCKER_REPOSITOR}/hzgc/peoman-worker:${VERSION}
    depends_on:
    - zookeeper
    - eureka
    - mysql
    container_name: peoman-worker
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - COMPARE_NUMBER=3
    - BIT_THRESHOLD=10
    - FLOAT_THRESHOLD=90
    - FLOAT_NEW_THRESHOLD=73
    - FLOAT_COMPARE_OPEN=true
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/GsFaceLib/face_libs
    - TZ=Asia/Shanghai
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - /opt/GsFaceLib:/opt/GsFaceLib
    - ${DOCKER_HOME}/peoman-worker/log:/log
    - /usr/lib64/ld-linux-x86-64.so.2:/lib/ld-linux-x86-64.so.2
    - /etc/localtime:/etc/localtime:ro

  dispatch-background:
    image: ${DOCKER_REPOSITOR}/hzgc/dispatch-background:${VERSION}
    depends_on:
    - kafka
    - mysql
    - eureka
    container_name: dispatch-background
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/GsFaceLib/face_libs
    - MYSQL_USERNAME=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - TZ=Asia/Shanghai
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - /opt/GsFaceLib:/opt/GsFaceLib
    - ${DOCKER_HOME}/dispatch-background/log:/log
    - /usr/lib64/ld-linux-x86-64.so.2:/lib/ld-linux-x86-64.so.2
    - /etc/localtime:/etc/localtime:ro

  face-dynrepo:
    image: ${DOCKER_REPOSITOR}/hzgc/face-dynrepo:${VERSION}
    depends_on:
    - zookeeper
    - esearch
    - eureka
    - collect
    container_name: face-dynrepo
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - ES_HOST=${ES_HOST}
    - TZ=Asia/Shanghai
    network_mode: "host"
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/face-dynrepo/log:/log
    - /usr/lib64/ld-linux-x86-64.so.2:/lib/ld-linux-x86-64.so.2
    - /etc/localtime:/etc/localtime:ro

  person-dynrepo:
    image: ${DOCKER_REPOSITOR}/hzgc/person-dynrepo:${VERSION}
    depends_on:
    - zookeeper
    - esearch
    - eureka
    - collect
    container_name: person-dynrepo
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - ES_HOST=${ES_HOST}
    - TZ=Asia/Shanghai
    network_mode: "host"
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/person-dynrepo/log:/log
    - /usr/lib64/ld-linux-x86-64.so.2:/lib/ld-linux-x86-64.so.2
    - /etc/localtime:/etc/localtime:ro

  vehicle-dynrepo:
    image: ${DOCKER_REPOSITOR}/hzgc/vehicle-dynrepo:${VERSION}
    depends_on:
    - zookeeper
    - esearch
    - eureka
    - collect
    container_name: vehicle-dynrepo
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - ES_HOST=${ES_HOST}
    - TZ=Asia/Shanghai
    network_mode: "host"
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/vehicle-dynrepo/log:/log
    - /usr/lib64/ld-linux-x86-64.so.2:/lib/ld-linux-x86-64.so.2
    - /etc/localtime:/etc/localtime:ro

  people:
    image: ${DOCKER_REPOSITOR}/hzgc/people:${VERSION}
    depends_on:
    - mysql
    - eureka
    - collect
    container_name: people
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - MYSQL_USERNAME=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - TZ=Asia/Shanghai
    extra_hosts:
    - platform:${PLATFORM_HOST}
    network_mode: "host"
    volumes:
    - ${DOCKER_HOME}/people/log:/log
    - /usr/lib64/ld-linux-x86-64.so.2:/lib/ld-linux-x86-64.so.2
    - /etc/localtime:/etc/localtime:ro

  dispatch:
    image: ${DOCKER_REPOSITOR}/hzgc/dispatch:${VERSION}
    depends_on:
    - mysql
    - eureka
    - collect
    container_name: dispatch
    network_mode: "host"
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - MYSQL_USERNAME=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - TZ=Asia/Shanghai
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/dispatch/log:/log
    - /usr/lib64/ld-linux-x86-64.so.2:/lib/ld-linux-x86-64.so.2
    - /etc/localtime:/etc/localtime:ro

  imsi-dynrepo:
    image: ${DOCKER_REPOSITOR}/hzgc/imsi-dynrepo:${VERSION}
    depends_on:
    - mysql
    - eureka
    - collect
    container_name: imsi-dynrepo
    network_mode: "host"
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - MYSQL_USERNAME=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - QUERY_TIME=30
    - TZ=Asia/Shanghai
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/imsi-dynrepo/log:/log
    - /usr/lib64/ld-linux-x86-64.so.2:/lib/ld-linux-x86-64.so.2
    - /etc/localtime:/etc/localtime:ro

  fusion:
    image: ${DOCKER_REPOSITOR}/hzgc/fusion:${VERSION}
    depends_on:
    - mysql
    - eureka
    - collect
    container_name: fusion
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - QUERY_TIME=30
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - TZ=Asia/Shanghai
    network_mode: "host"
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/fusion/log:/log
    - /usr/lib64/ld-linux-x86-64.so.2:/lib/ld-linux-x86-64.so.2
    - /etc/localtime:/etc/localtime:ro
