- hosts: kafka_servers
  remote_user: root
  roles:
  - roles

  tasks:
    - name: chmod permission
      shell: chmod +x {{BigdataDir}}/kafka/bin/*
    - name: start kafka
      shell: sh {{BigdataDir}}/kafka/bin/kafka-server-start.sh -daemon {{BigdataDir}}/kafka/config/server.properties &
      tags:
      - start kafka
    - name: start kafka-manager
      shell: nohup {{BigdataDir}}/kafka/kafka-manager/bin/kafka-manager &
      tags:
      - kafkaManagerStart


- hosts: kafka_extend_servers
  remote_user: root
  roles:
  - roles

  tasks:
    - name: chmod permission
      shell: chmod +x {{BigdataDir}}/kafka/bin/*
    - name: start kafka
      shell: sh {{BigdataDir}}/kafka/bin/kafka-server-start.sh -daemon {{BigdataDir}}/kafka/config/server.properties &
      tags:
      - start extend kafka
    - name: start kafka-manager
      shell: nohup {{BigdataDir}}/kafka/kafka-manager/bin/kafka-manager &
      tags:
      - kafkaManagerStart
