version: '2.3'

services:

  people:
    image: ${DOCKER_REPOSITOR}/hzgc/people:${PEOPLE_VERSION}
    container_name: people
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - MYSQL_USERNAME=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    extra_hosts:
    - platform:${PLATFORM_HOST}
    network_mode: "host"

  imsi-dynrepo:
    image: ${DOCKER_REPOSITOR}/hzgc/imsi-dynrepo:${IMSI_DYNREPO_VERSION}
    container_name: imsi-dynrepo
    network_mode: "host"
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - MYSQL_USERNAME=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - QUERY_TIME=30
    - TAG=1
    extra_hosts:
    - platform:${PLATFORM_HOST}

  fusion:
    image: ${DOCKER_REPOSITOR}/hzgc/fusion:${FUSION_VERSION}
    container_name: fusion
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - QUERY_TIME=30
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    network_mode: "host"
    extra_hosts:
    - platform:${PLATFORM_HOST}
    
  peoman-worker:
    image: ${DOCKER_REPOSITOR}/hzgc/peoman-worker:${PEOMAN_WORKER_VERSION}
    container_name: peoman-worker
    network_mode: "host"
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - COMPARE_NUMBER=3
    - BIT_THRESHOLD=10
    - FLOAT_THRESHOLD=90
    - FLOAT_NEW_THRESHOLD=73
    - FILTER_INTERVAL_TIME=10
    - UPDATE_INNER_FEATURE_TIME=3600
    - FLOAT_COMPARE_OPEN=true
    - SHARPNESS_OPEN=true
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - MYSQL_USERNAME=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - /opt/GsFaceLib:/opt/GsFaceLib
