version: '2.3'

services:
  collect:
    image: ${DOCKER_REPOSITOR}/hzgc/collect:${COLLECT_VERSION}
    container_name: collect
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    network_mode: "host"
    extra_hosts:
    - platform:${PLATFORM_HOST}

  facecompare:
    image: ${DOCKER_REPOSITOR}/hzgc/facecompare:${FACECOMPARE_VERSION}
    container_name: facecompare
    restart: always
    environment:
    - ZK_ADDRESS=${ZK_HOST}:${ZK_PORT}
    - ES_HOST=${ES_HOST}
    - KAFKA_SERVERS=${KAFKA_HOST}:${KAFKA_PORT}
    network_mode: "host"
    volumes:
    - ${DOCKER_HOME}/facecompare/log:/worker/log
    - /opt/GsFaceLib:/opt/GsFaceLib
    - ${DOCKER_HOME}/facecompare/data:/worker/matedata