version: '2.3'

services:
  eureka:
    image: registry.cn-hangzhou.aliyuncs.com/gosun/registry
    container_name: eureka
    restart: always
    hostname: eureka
    #network_mode: "host"
    ports:
    - "9000:9000"

  mysql:
    image: ${DOCKER_REPOSITOR}/hzgc/mysql:5.7.19
    container_name: mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    hostname: mysql
    ports:
    - "3306:3306"
    volumes:
    - ${DOCKER_HOME}/mysql/data:/var/lib/mysql
    - ${DOCKER_HOME}/mysql/sql/peopleDatabase.sql:/docker-entrypoint-initdb.d/peopleDatabase.sql

  mysql-cron:
    image: ${DOCKER_REPOSITOR}/hzgc/mysql-cron:5.7.19
    container_name: mysql-cron
    restart: always
    links:
    - mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    - ${DOCKER_HOME}/mysql/crontab/cronfile:/cronfile
    - ${DOCKER_HOME}/mysql/crontab:/crontab
    - ${DOCKER_HOME}/mysql/sql:/mysql

  zookeeper:
    image: ${DOCKER_REPOSITOR}/hzgc/zookeeper:3.4.10
    container_name: zookeeper
    restart: always
    hostname: zookeeper
    ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
    volumes:
    - ${DOCKER_HOME}/zookeeper/data:/data
    - ${DOCKER_HOME}/zookeeper/datalog:/datalog

  kafka:
    image: ${DOCKER_REPOSITOR}/hzgc/kafka:1.0.0
    container_name: kafka
    restart: always
    #network_mode: "host"
    depends_on:
    - zookeeper
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${DOCKER_HOST_IP}:${KAFKA_PORT}
    - KAFKA_CREATE_TOPICS=face:1:1,car:1:1,person:1:1
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    hostname: kafka
    ports:
    - "9092:9092"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${DOCKER_HOME}/kafka/kafka-logs-kafka/:/kafka/kafka-logs-kafka/
    - ${DOCKER_HOME}/kafka/logs:/opt/kafka/logs

  esearch:
    image: ${DOCKER_REPOSITOR}/hzgc/elasticsearch-ik:5.5.0
    container_name: esearch
    restart: always
    environment:
    - discovery.type=single-node
    - cluster.name=hbase2es-cluster
    - node.name=172.18.18.201
    - network.host=172.18.18.201
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    hostname: esearch
    privileged: true
    network_mode: "host"
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - ${DOCKER_HOME}/es/data:/usr/share/elasticsearch/data

  kibana:
    image: ${DOCKER_REPOSITOR}/hzgc/kibana:5.5.0
    depends_on:
    - esearch
    container_name: kibana
    restart: always
    environment:
    - SERVER_NAME=$DOCKER_HOST_IP
    - ELASTICSEARCH_URL=http://${ES_HOST}:${ES_PORT}
    ports:
    - "5601:5601"

  collect:
    image: ${DOCKER_REPOSITOR}/hzgc/collect:${VERSION}
    depends_on:
    - zookeeper
    - eureka
    - mysql
    container_name: collect
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    network_mode: "host"
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/collect/log:/log

  peoman-worker:
    image: ${DOCKER_REPOSITOR}/hzgc/peoman-worker:${VERSION}
    depends_on:
    - zookeeper
    - eureka
    - mysql
    container_name: peoman-worker
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - COMPARE_NUMBER=3
    - BIT_THRESHOLD=10
    - FLOAT_THRESHOLD=90
    - FLOAT_NEW_THRESHOLD=73
    - FLOAT_COMPARE_OPEN=true
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - /opt/GsFaceLib:/opt/GsFaceLib
    - ${DOCKER_HOME}/peoman-worker/log:/log

  dispatch-background:
    image: ${DOCKER_REPOSITOR}/hzgc/dispatch-background:${VERSION}
    depends_on:
    - kafka
    - mysql
    - eureka
    container_name: dispatch-background
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/GsFaceLib/face_libs
    - MYSQL_USERNAME=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - /opt/GsFaceLib:/opt/GsFaceLib
    - ${DOCKER_HOME}/dispatch-background/log:/log

  kafka-parquet:
    image: ${DOCKER_REPOSITOR}/hzgc/spark:${VERSION}
    depends_on:
    - zookeeper
    - kafka
    - esearch
    container_name: kafka-parquet
    command: /start-kafka-to-parquet.sh
    restart: always
    network_mode: "host"
    environment:
    - TZ=Asia/Shanghai
    extra_hosts:
    - platform:${PLATFORM_HOST}
    - ${DOCKER_HOST_NAME}:${DOCKER_HOST_IP}
    volumes:
    - ${DOCKER_HOME}/spark/sparkJob.properties:/usr/spark-2.2.0/conf/sparkJob.properties
    - ${DOCKER_HOME}/spark/parquet:/parquet
    - /usr/lib64/ld-linux-x86-64.so.2:/lib/ld-linux-x86-64.so.2
    - /etc/localtime:/etc/localtime:ro

  kafka-tidb:
    image: ${DOCKER_REPOSITOR}/hzgc/spark:${VERSION}
    depends_on:
    - zookeeper
    - kafka
    - esearch
    container_name: kafka-tidb
    command: /start-kafka-to-tidb.sh
    restart: always
    network_mode: "host"
    environment:
    - TZ=Asia/Shanghai
    extra_hosts:
    - platform:${PLATFORM_HOST}
    - ${DOCKER_HOST_NAME}:${DOCKER_HOST_IP}
    volumes:
    - ${DOCKER_HOME}/spark/sparkJob.properties:/usr/spark-2.2.0/conf/sparkJob.properties
    - /usr/lib64/ld-linux-x86-64.so.2:/lib/ld-linux-x86-64.so.2
    - /etc/localtime:/etc/localtime:ro

  face-dynrepo:
    image: ${DOCKER_REPOSITOR}/hzgc/face-dynrepo:${VERSION}
    depends_on:
    - zookeeper
    - esearch
    - eureka
    - collect
    container_name: face-dynrepo
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - ES_HOST=${ES_HOST}
    network_mode: "host"
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/face-dynrepo/log:/log

  person-dynrepo:
    image: ${DOCKER_REPOSITOR}/hzgc/person-dynrepo:${VERSION}
    depends_on:
    - zookeeper
    - esearch
    - eureka
    - collect
    container_name: person-dynrepo
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - ES_HOST=${ES_HOST}
    network_mode: "host"
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/person-dynrepo/log:/log

  vehicle-dynrepo:
    image: ${DOCKER_REPOSITOR}/hzgc/vehicle-dynrepo:${VERSION}
    depends_on:
    - zookeeper
    - esearch
    - eureka
    - collect
    container_name: vehicle-dynrepo
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - ES_HOST=${ES_HOST}
    network_mode: "host"
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/vehicle-dynrepo/log:/log

  people:
    image: ${DOCKER_REPOSITOR}/hzgc/people:${VERSION}
    depends_on:
    - mysql
    - eureka
    - collect
    container_name: people
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - MYSQL_USERNAME=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    extra_hosts:
    - platform:${PLATFORM_HOST}
    network_mode: "host"
    volumes:
    - ${DOCKER_HOME}/people/log:/log

  dispatch:
    image: ${DOCKER_REPOSITOR}/hzgc/dispatch:${VERSION}
    depends_on:
    - mysql
    - eureka
    - collect
    container_name: dispatch
    network_mode: "host"
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - MYSQL_USERNAME=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/dispatch/log:/log

  imsi-dynrepo:
    image: ${DOCKER_REPOSITOR}/hzgc/imsi-dynrepo:${VERSION}
    depends_on:
    - mysql
    - eureka
    - collect
    container_name: imsi-dynrepo
    network_mode: "host"
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - MYSQL_USERNAME=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - QUERY_TIME=30
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/imsi-dynrepo/log:/log

  fusion:
    image: ${DOCKER_REPOSITOR}/hzgc/fusion:${VERSION}
    depends_on:
    - mysql
    - eureka
    - collect
    container_name: fusion
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - QUERY_TIME=30
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    network_mode: "host"
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/fusion/log:/log

  collect-ftp:
    image: ${DOCKER_REPOSITOR}/hzgc/collect-ftp:1.0
    container_name: collect-ftp
    restart: always
    runtime: nvidia
    depends_on:
    - kafka
    - zookeeper
    hostname: collect-ftp
    environment:
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - HOST_IP=${DOCKER_HOST_IP}
    - DETECTOR_NUMBER=6
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - SEEMMO_URL=http://${SEEMO_URL}:7000/ImgProcService/Recognize
    - HOME_DIR=/opt/ftpdata
    - BACKUP_DIR=/home/ftpdata
    - DETECTOR_ENABLE=true
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/GsFaceLib/face_libs
    - TZ=Asia/Shanghai
    network_mode: "host"
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/collect-ftp/log:/log
    - /opt/GsFaceLib:/opt/GsFaceLib
    - /lib64:/lib64
    - /usr/lib64/ld-linux-x86-64.so.2:/lib/ld-linux-x86-64.so.2
    - /opt/ftpdata:/opt/ftpdata
    - /home/ftpdata:/home/ftpdata
    - /etc/localtime:/etc/localtime:ro

  facecompare:
    image: ${DOCKER_REPOSITOR}/hzgc/facecompare:${VERSION}
    container_name: facecompare
    restart: always
    depends_on:
    - zookeeper
    - kafka
    - esearch
    environment:
    - ZK_ADDRESS=${ZK_HOST}:${ZK_PORT}
    - ES_HOST=${ES_HOST}
    - KAFKA_SERVERS=${KAFKA_HOST}:${KAFKA_PORT}
    network_mode: "host"
    volumes:
    - ${DOCKER_HOME}/facecompare/log:/worker/log
    - /opt/GsFaceLib:/opt/GsFaceLib
    - ${DOCKER_HOME}/facecompare/data:/worker/matedata