- hosts: es_servers
  remote_user: root
  roles:
  - roles

  tasks:
   - name: change owner and group
     file: path={{BigdataDir}}/elastic owner=elsearch group=elsearch recurse=yes
   - name: source env
     shell: source /etc/profile
   - name: make elastic permission
     shell: su - elsearch  -c 'chmod +x {{BigdataDir}}/elastic/bin/*'
   - name: start es
     remote_user: root
     shell: su - elsearch  -c '{{BigdataDir}}/elastic/bin/elasticsearch -d'
     tags:
     - start elasticsearch

