- hosts: hadoop_servers
  remote_user: root
  roles:
  - roles

  tasks:
   - name: install dependency package
     yum: name={{ item }} state=present
     with_items:
     - openssh
     - rsync
   - name: copy and unzip hadoop
     unarchive: src=/opt/ansible/roles/files/hadoop.tar.gz dest={{BigdataDir}}
   - name: create hadoop logs directory
     file: dest={{BigdataDir}}/hadoop/logs mode=0775 state=directory
   - name: install configuration file hadoop-env.sh.j2 for hadoop
     template: src=/opt/ansible/roles/templates/hadoop-env.sh.j2 dest={{BigdataDir}}/hadoop/etc/hadoop/hadoop-env.sh
   - name: install configuration file core-site.xml.j2 for hadoop
     template: src=/opt/ansible/roles/templates/core-site.xml.j2 dest={{BigdataDir}}/hadoop/etc/hadoop/core-site.xml
   - name: install configuration file hdfs-site.xml.j2 for hadoop
     template: src=/opt/ansible/roles/templates/hdfs-site.xml.j2 dest={{BigdataDir}}/hadoop/etc/hadoop/hdfs-site.xml
   - name: install configuration file slaves.j2 for hadoop
     template: src=/opt/ansible/roles/templates/slaves.hadoop.j2 dest={{BigdataDir}}/hadoop/etc/hadoop/slaves
   - name: change shell sbin file
     shell: chmod 755 {{BigdataDir}}/hadoop/sbin/*
   - name: change shell bin file
     shell: chmod 755 {{BigdataDir}}/hadoop/bin/*
   - name: start journalnode
     shell: sh {{BigdataDir}}/hadoop/sbin/hadoop-daemon.sh start journalnode
     become: true
     become_method: su
     become_user: root
     when: datanode == "true"
   - name: format active namenode hdfs
     shell: sh {{BigdataDir}}/hadoop/bin/hdfs namenode -format -force
     become: true
     become_method: su
     become_user: root
     when: namenode_active == "true"
   - name: start active namenode hdfs
     shell: sh {{BigdataDir}}/hadoop/sbin/hadoop-daemon.sh start namenode
     become: true
     become_method: su
     become_user: root
     when: namenode_active == "true"
   - name: format standby namenode hdfs
     shell: sh {{BigdataDir}}/hadoop/bin/hdfs namenode -bootstrapStandby -force
     become: true
     become_method: su
     become_user: root
     when: namenode_standby == "true"
   - name: stop active namenode hdfs
     shell: sh {{BigdataDir}}/hadoop/sbin/hadoop-daemon.sh stop namenode
     become: true
     become_method: su
     become_user: root
     when: namenode_active == "true"
   - name: format ZKFC
     shell: sh {{BigdataDir}}/hadoop/bin/hdfs zkfc -formatZK -force
     become: true
     become_method: su
     become_user: root
     when: namenode_active == "true"
   - name: stop journalnode
     shell: sh {{BigdataDir}}/hadoop/sbin/hadoop-daemon.sh stop journalnode
     become: true
     become_method: su
     become_user: root
     when: datanode == "true"
     tags:
      - format hadoop
