- hosts: kafka_servers
  remote_user: root
  roles:
  - roles

  tasks:
    - name: chmod permission
      shell: chmod +x {{BigdataDir}}/kafka/bin/*
    - name: start kafka
      shell: sh {{BigdataDir}}/kafka/bin/kafka-server-start.sh -daemon {{BigdataDir}}/kafka/config/server.properties &
      tags:
      - start kafka


- hosts: kafka_extend_servers
  remote_user: root
  roles:
  - roles

  tasks:
    - name: chmod permission
      shell: chmod +x {{BigdataDir}}/kafka/bin/*
    - name: start kafka
      shell: sh {{BigdataDir}}/kafka/bin/kafka-server-start.sh -daemon {{BigdataDir}}/kafka/config/server.properties &
      tags:
      - start kafka
