- hosts: kafka_extend_servers
  remote_user: root
  roles:
  - roles

  tasks:
    - name: mkdir jdk directory
      file: path={{BigdataDir}} state=directory mode=0755
    - name: copy and unzip kafka
      unarchive: src=/opt/ansible/roles/files/kafka.tar.gz dest={{BigdataDir}}
    - name: mkdir dir for kafka logs
      file: dest={{BigdataDir}}/kafka/logs mode=0755 state=directory
    - name: install configuration file for kafka-manager
      template: src=/opt/ansible/roles/templates/application.conf.j2 dest={{BigdataDir}}/kafka/kafka-manager/conf/application.conf
    - name: install configuration file for kafka
      template: src=/opt/ansible/roles/templates/server.properties.j2 dest={{BigdataDir}}/kafka/config/server.properties
      tags:
      - install kafka


- hosts: kafka_servers
  remote_user: root
  roles:
  - roles

  tasks:
    - name: install configuration file for kafka-manager
      template: src=/opt/ansible/roles/templates/application.conf.j2 dest={{BigdataDir}}/kafka/kafka-manager/conf/application.conf
    - name: install configuration file for kafka
      template: src=/opt/ansible/roles/templates/server.properties.j2 dest={{BigdataDir}}/kafka/config/server.properties
      tags:
      - change kafka conf

