- hosts: zk_servers
  remote_user: root
  roles:
  - roles

  tasks:
    - name: start zookeeper
      shell: source /etc/profile; sh {{BigdataDir}}/zookeeper/bin/zkServer.sh start
      tags:
      - start zookeeper
