- hosts: zk_servers
  remote_user: root
  roles:
  - roles

  tasks:
   - name: source env
     shell: source /etc/profile
   - name: chmod +x
     shell: chmod +x {{BigdataDir}}/zookeeper/bin/zkServer.sh
   - name: stop zookeeper
     shell: source /etc/profile; sh {{BigdataDir}}/zookeeper/bin/zkServer.sh stop
     tags:
     - stop zookeeper
