- hosts: zk_servers
  remote_user: root
  roles:
  - roles

  tasks:
    - name: mkdir directory for bigdata data
      file: dest={{BigdataDir}} mode=0755 state=directory
    - name: install zookeeper
      unarchive: src=/opt/ansible/roles/files/zookeeper-3.4.10.tar.gz dest={{BigdataDir}}
    - name: install configuration file for zookeeper
      template: src=/opt/ansible/roles/templates/zoo.cfg.j2 dest={{BigdataDir}}/zookeeper/conf/zoo.cfg
    - name: create log directory
      file: dest={{BigdataDir}}/zookeeper/dataLogDir mode=0755 state=directory
    - name: add myid file {{ myid }}
      shell: echo {{ myid }} > {{BigdataDir}}/zookeeper/dataDir/myid
    - name: start zookeeper
      shell:  sh {{BigdataDir}}/zookeeper/bin/zkServer.sh start
      tags:
      - start zookeeper

