version: '2.3'

services:

  fusion:
    image: ${DOCKER_REPOSITOR}/hzgc/fusion:${FUSION_VERSION}
    depends_on:
    - collect
    container_name: fusion
    restart: always
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - QUERY_TIME=30
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    network_mode: "host"
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - ${DOCKER_HOME}/fusion/log:/log